In [43]:
import pandas as pd

# here upload dataset
df = pd.read_csv("../data/train.csv.zip")

print(f"Dataset Size: {df.shape}")
df.head()

Dataset Size: (9800, 18)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [ ]:
here why we used ..means "takes one step backward  out of the current folder"(present we are in notebooks folder)
/ means look inside
data/ means "go forward into the folder named data
train.csv.zip means "open specific file."

In [44]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
step 1: Removing duplicates

In [46]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9795    False
9796    False
9797    False
9798    False
9799    False
Length: 9800, dtype: bool

In [ ]:
it goes to entire dataset,line by line
it marks every row as false or (true)if it is unique

In [47]:
print(df.duplicated().sum())#here we counted how many double rows are in the data

0

In [48]:
df.duplicated().sum()# why i used this because it counts all the true values from the previous step
#it shows 0 means superstore dataset is already clean and doesnt contain any repeated rows

np.int64(0)

In [49]:
#here it deletes any duplicate rows found.but we already got 0 ,it didnt need to remove anything
df=df.drop_duplicates()

In [50]:
df.shape

(9800, 18)

In [51]:
#it scans every single cell in our huge data tables
#it repaces our actual data values with true or false words
# false means cell is not empty(it contain real data like a name,date,or numbers)
# true means the cell is blank or empty
df.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9796,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9797,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
#instead of reading 1000 rows,it gives us a clean checklist.if a column shows 0,it means it is fully complete
df.isnull().sum()#these are the empty cells present in each column

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [32]:
# fillna(0) it fills every blank cell in this column,and fill it with a 0
df['Postal Code']=df['Postal Code'].fillna(0)

In [33]:
print(df['Postal Code'].isnull().sum())

0

In [34]:
# here we are converting text format date into date format
df['Order Date'] = pd.to_datetime(df['Order Date'],format="mixed")
df['Ship Date'] = pd.to_datetime(df['Ship Date'],format="mixed")

In [35]:
print(df[["Order Date","Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [36]:
print(df[['Order Date','Ship Date']].head())

  Order Date  Ship Date
0 2017-08-11 2017-11-11
1 2017-08-11 2017-11-11
2 2017-12-06 2017-06-16
3 2016-11-10 2016-10-18
4 2016-11-10 2016-10-18

In [37]:
df["Sales"]

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9795      3.7980
9796     10.3680
9797    235.1880
9798     26.3760
9799     10.3840
Name: Sales, Length: 9800, dtype: float64

In [38]:
df["Sales"].sum()

np.float64(2261536.7827000003)

In [39]:
print("Highest sale in our data:",df["Sales"].max())

Highest sale in our data: 22638.48

In [40]:
df_clean=df[df["Sales"]<2000]

In [41]:
print("Total rows left after cleaning:",len(df_clean))

Total rows left after cleaning: 9663

In [42]:
# Save your clean data into a brand new file
df_clean.to_csv("../data/superstore_sales_clean.csv", index=False)

print("File saved successfully!")

File saved successfully!